Alter mda method
NTD-Modelling-Consortium/ntd-model-trachoma pull request #58
Opened 2024-07-16 08:31 UTC by mattg3004

2024-07-24 14:15 UTC, tlestang requested changes
I've left the tests aside for now. I think I was quite thorough, so don't be alarmed by the number of comments! They're all about style and/or efficiency.

2024-07-24 14:15 UTC, tlestang commented on trachoma/trachoma_functions.py
> +    cov = MDAData[MDA_round_current][3]
This makes me think elements of `MDAData` should be instances of a small dataclass or named tuple.

2024-07-24 14:15 UTC, tlestang commented on trachoma/trachoma_functions.py
> +    nDoses[MDAData[MDA_round_current][-2]] += out[1]
What is `out`? And why selection the penultimate index? I'd suggest a couple of comments.

2024-07-24 14:15 UTC, tlestang commented on trachoma/trachoma_functions.py
> +    coverage[MDAData[MDA_round_current][-2]] += out[1]/ len(np.where(np.logical_and(vals['Age'] > ageStart * 52, vals['Age'] <= ageEnd *52))[0])
Again, the call to `np.where` could be removed in favor of manipulating boolean arrays directly:
```python
out[1] / np.count_nonzero((vals['Age'] > ageStart * 52) & (vals['Age'] <= ageEnd * 52))
```
I'd argue this is more readable, but that's certainly [faster](https://stackoverflow.com/questions/67468493/boolean-indexing-vs-np-where).

2024-07-25 09:47 UTC, tlestang requested changes
Thank you @mattg3004 for taking the time to add these tests. I realise it's extra work but it will make further developments faster (and probably made it easier for you to implement these changes already?)

My main concern is that the tests duplicate the implementation of the MDA loop. We usually try to avoid this because it couples the test code to the actual implemenation of the code under test. For instance, if someone decides to rename `check_if_we_need_to_redraw_probability_of_treatment`, or `MDA_time_Age_range`, all the tests will fail -- when actually all that was done was renaming symbols.

Instead we would rather test the _functions_ that are components of the code under test (here the MDA loop): for instance `MDA_timestep_Age_range`. Then if tests on these functions pass, then you know that any issue would lie in the way the MDA loop is implemented, in the code that calls these functions or above. 

Now -- and that's what you aimed for -- it's also useful to have a test testing the implementation of the MDA loop, because there is room for mistakes. Then you have two options:

1. You test around the function that contains this MDA loop, i.e. `sim_Ind_MDA`
2. You wrap the mda loop logic into a new function, that you test.

(2) is the preferred option!

2024-07-25 09:47 UTC, tlestang commented on tests/test_updatedMDA.py
> +        npt.assert_allclose(np.mean(propCured), expectedProportionCured, atol=0, err_msg="The values are not close enough")
Same here. I would in fact replace those two tests `testMDAOnNonBabies` and `testNotTreatingOutsideOfTargetAgeRange` by a single test on `MDA_timestep_Age_range` which I think is what is _really_ being tested here. Additionally, instead of repeating the MDA rounds 100 time to get converged statistics, you could set the return value of (patch) `numpy.random.uniform`.

```python
def myuniform(size):
    # Set that only the first 10 individuals are treated/cured down in DoMDATimeRange
    return np.array([1.] * 10 + [0.] * (size - 10))
np.random.uniform = myuniform

# Set tment probability to something we can control
valsTest['treatProbability'] = np.array([0.5] * params['N'])

out = MDA_timestep_Age_range(...)
valsTest = out[0]

# ... Do assertions on valsTest ..
```

2024-07-25 09:47 UTC, tlestang commented on tests/test_updatedMDA.py
> +        npt.assert_equal(actual = rank1, desired = rank2)
I would only have this assertion, because the two following assertions test the computation of the proability values, rather that the fact that rank-correlation is maintained. That being said there could be a separate test around `drawTreatmentProbabilties`.

2024-07-25 14:40 UTC, thk123 commented on trachoma/trachoma_functions.py
> +        systematic_non_compliance = systematic_non_compliance
I think you're suggesting using `snc` instead of `systematic_non_compliance` - I'm generally of the view accronyms increase the cognitive load of understanding a piece of code  so I'm disinclined to agree - but probably out of scope of this PR to change all SNCs to the expanded version. While those familiar with this specific project are probably familar enough with the acronym that it doesn't have a big impact in cognitive load, there are multiple different terms used for this concept (e.g. adherence) so I think it probably increases cognitive load for people like me, who aren't as familiar with the domain, but also people who use a different term.

2024-07-25 15:05 UTC, thk123 commented on trachoma/trachoma_functions.py
> +    nDoses[MDAData[MDA_round_current][-2]] += out[1]
I was not able to figure out the significance of `-2` - it looks like from usage that it is the index of the drug type, but unfortunately I can't follow the logic of `readPlatformData` and I think a wrong comment is probably worse than no comment. I've at least done something with the `out[1]`,

2024-07-25 16:38 UTC, thk123 commented on trachoma/trachoma_functions.py
> +    coverage[MDAData[MDA_round_current][-2]] += out[1]/ len(np.where(np.logical_and(vals['Age'] > ageStart * 52, vals['Age'] <= ageEnd *52))[0])
This works, and I do think it is clearer, but I have to admit I find numpy a little confusing here, perahaps you can explain how come

```
a = np.arange(1, 10)
a>2 & a<4
```
Gives me an error, but 
```
(a>2) & (a<4)
```
Gives the `[False, False, True, False,....]` I was expecting? Like shouldn't it _already_ be evaluating the two subconditions first?

2024-07-26 07:10 UTC, tlestang commented on trachoma/trachoma_functions.py
> +        systematic_non_compliance = systematic_non_compliance
I am actually in favor of using the longer form, for all the reasons you mention.

2024-07-26 07:54 UTC, tlestang commented on trachoma/trachoma_functions.py
> +    coverage[MDAData[MDA_round_current][-2]] += out[1]/ len(np.where(np.logical_and(vals['Age'] > ageStart * 52, vals['Age'] <= ageEnd *52))[0])
That's because `&` has precedence over `<` and `>`. So `a>2 & a<4` is evaluated as `a > (2 & a) < 4`.

And in Python `x < y < z` is equivalent to `x < y and y < z` which applies `and` between two NumPy arrays and leads to the `ValueError`.

2024-07-29 09:27 UTC, thk123 commented on tests/test_endtoend.py
> +        np.random.set_state(numpy_states[0])
The test works without it so I've removed it, but when @mattg3004 is back we can discuss if there is something I've misunderstood.

2024-07-29 11:32 UTC, thk123 commented on tests/test_updatedMDA.py
> +        expectedProportionCured = 0.5 * self.params['MDA_Eff'] * cov
I see what you're saying - and I agree this looks wrong, but without `check_if...` then the tests fail. I think this function call is required because the setup function sets the `MDA_coverage` key to 0.1, I think this can be fixed by pulling out the setup. I also think the inner loop is redundant as there is always just a single value - I will see if I can tidy this up a bit having understood it, but I do think `cov` is not mutated so this is testing the right thing,

2024-07-29 14:23 UTC, thk123 commented on tests/test_updatedMDA.py
> +        expectedProportionCured = 0.5 * self.params['MDA_Eff'] * cov
I think I will leave this for when Matt is back - I think we should be able to get rid of this, but it is a bit fiddly to keep all the tests working and I'm happy the assumption is correct.

2024-07-29 14:27 UTC, thk123 commented on tests/test_updatedMDA.py
> +        npt.assert_allclose(np.mean(propCured), expectedProportionCured, atol=5e-03, err_msg="The values are not close enough")
I think I disagree with this one: this tests that the 0.5 efficacy effect for babies is respected but not applied for adults. That is, this test is specifically testing line 298 of trachoma_functions.py

2024-08-02 15:34 UTC, tlestang commented on tests/test_updatedMDA.py
> +        npt.assert_allclose(np.mean(propCured), expectedProportionCured, atol=5e-03, err_msg="The values are not close enough")
> this tests that the 0.5 efficacy effect for babies is respected but not applied for adults

Yes, but isn't this just a test of `np.where`? I think my problem with this `testMDAOnNonBabies` is that it adds 23 lines of test code (22 of which are identical from the preceding test), in order to test what is essentially duplicate statements.  Looks to me like we could have a single case that tests that given an age range and efficacy number, individuals are treated and cured as expected. 

Not a blocker for me though if you're not convinced ;)

2024-08-04 07:14 UTC, tlestang commented on tests/test_updatedMDA.py
> +        npt.assert_array_equal(treatedPeople, [0, 1])
Thanks @thk123 this is very much what I had in mind. Note that one downside of mocking random number generation in this way is that the test is coupled to the implementation of the function under test. For instance if the calls to `np.random.uniform` are reordered then the test is likely to break? In my view this is preferable to relying on converged statistics with an arbitrary tolerance -- what do you think?

2024-08-06 09:04 UTC, tlestang approved these changes

2024-08-06 10:09 UTC, merged